services:
# This is the database in which the events are stored
  db:
    container_name: backend-db
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-network
    environment:
      - POSTGRES_DB=backend-db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
secrets:
  db-password:
    file: db/password.txt
networks:
  backend-network:
volumes:
  db-data: